# Generated by Django 3.2.17 on 2023-02-24 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newswebsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='abstract',
            field=models.TextField(verbose_name='摘要'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author_avatar',
            field=models.FileField(upload_to='author_avatar', verbose_name='作者头像'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author_desc',
            field=models.CharField(max_length=100, verbose_name='作者签名'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author_name',
            field=models.CharField(max_length=100, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cate', to='newswebsite.category', verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.FileField(upload_to='article_image', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='article',
            name='intro',
            field=models.CharField(max_length=1000, verbose_name='导语'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publish_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=100, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='best',
            name='select_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='select_article', to='newswebsite.article', verbose_name='精选文章'),
        ),
        migrations.AlterField(
            model_name='best',
            name='select_reason',
            field=models.CharField(choices=[('今日新闻', '今日新闻'), ('首页推荐', '首页推荐'), ('编辑推荐', '编辑推荐')], max_length=50, verbose_name='推荐'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=40, verbose_name='分类名'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='belong_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='newswebsite.article', verbose_name='文章'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='belong_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='评论者'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='评论时间'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='words',
            field=models.CharField(max_length=200, verbose_name='评论内容'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.FileField(upload_to='avatar', verbose_name='用户头像'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='belong_to',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
